#pragma once

#define KS_BUS_CMD_DISPATCH "B_CMD_DISPATCH"
#define KS_BUS_CMD_TRANSMIT "B_CMD_TRANSMIT"

#define KS_BUS_FILE_MANAGER "B_FILE_MANAGER"

#define KS_BUS_HEALTH_PING  "B_HEALTH_PING"
#define KS_BUS_HEALTH_PONG  "B_HEALTH_PONG"
