#pragma once

#define KS_COMPONENT_CMD_DISPATCH       "CA_CMD_DISPATCHER"
#define KS_COMPONENT_CMD_LISTENER       "CA_CMD_LISTENER"
#define KS_COMPONENT_CMD_TRANSMITTER    "CQ_CMD_TRANSMITTER"

#define KS_COMPONENT_FILE_MANAGER       "CQ_FILE_MANAGER"

#define KS_COMPONENT_HOUSEKEEPING       "CA_HOUSEKEEPING"

#define KS_COMPONENT_PARAMETER_DB       "CQ_PARAM_DB"

#define KS_COMPONENT_SCHEDULER          "CP_SCHEDULER"
